### PR TITLE
Adding react-intl

### PR DESCRIPTION
**Pull request by sirrodgepodge**
Hey dudes,

Went ahead and added React-Intl, didn't see where anyone had done this, it's a bit hairy to work with but pretty awesome once it's up and running.

Visit '/intl' route to check it out in action.

The native Intl package has some basic translations of numbers and dates included I believe (needs to be polyfilled for Safari, took care of that).

React-Intl includes a bunch of additional convenient translations for you, such as relative dates (e.g. yesterday, two weeks from now) as well as a convenient way to plug in your own locale-specific translations for page content, see '/modules/Intl/setup/localizationData/'.

**One bug that's happening now that I can't figure out:**  I get this error message saying 'server-side render discarded'.  No idea what's causing this, probably something small.  I figured one of you might know and then we can fix that and merge this furrealz (feel free to style and integrate as you choose, I never use bootstrap and am not sure how you want user "flow" to be so I pretty much just plopped every React-Intl element on a page haha).

Best,
Rodge

### CODE REVIEW

**Comment by somus** [comment]
@sirrodgepodge 🍻  Great Work! Right in time for V2.

I think we don't need separate intl page. We can have the language switcher in the header itself.
I'll integrate react-intl with rest of the demo. I'll also take a look at the bug.

**Comment by somus** [comment]
Hey @sirrodgepodge 

I've removed the demo page, added react-intl components to all other pages and added the language switcher in the header. I've opened a new PR with these changes. So, I'm closing this.

Thank you very much for the PR!

**Comment by sirrodgepodge** [comment]
No problem Somus!  Yea of course I don't mind you incorporating as you see fit :).  I figured you wouldn't want a whole page dedicated to react-intl, just wanted to demo all the features and let you guys pick and choose how/what to add.

Did you figure out where that bug was coming from???

**Comment by somus** [comment]
I didn't face any bug while running. Pull the latest code and check whether the bug is occurring for you.

**Pull request closed without merging**
