### PR TITLE
Consistent formatting and highlighting

### PR DESCRIPTION
**Pull request by KleoPetroff**
Consistency across the README.md with a little highlighting improvement on the router code.

### CODE REVIEW

**Comment by beaucharman** [comment]
+1

**Comment by prank7** [comment]
Thanks @KleoPetroff. Merged.

**Comment by prank7** [comment]
Thanks @KleoPetroff. Merged this time. :+1:

**Comment by KleoPetroff** [comment]
@prank7, nice! I was behind the latest commits from today. :)

**Comment by beaucharman** [comment]
Also addressed https://github.com/Hashnode/mern-starter/issues/29

**Pull request merged**
