### PR TITLE
Import 'babel-polyfill' in the webpack entry point files for better browser support

### PR DESCRIPTION
**Pull request by yn5**

### CODE REVIEW

**Comment by carloscuatin** [comment]
👍 LGTM

**Comment by yn5** [comment]
@alkshendra @fazlerocks @mayankchd @sandeeppanda92 Could this get merged please?

**Comment by mayankchd** [comment]
Thanks @yn5 !

**Comment by yn5** [comment]
Thanks for merging @mayankchd!

**Pull request merged**
