### PR TITLE
React Helmet 

### PR DESCRIPTION
**Pull request by rdiazv**
Using [React Helmet](https://github.com/nfl/react-helmet) to manage `head` elements (`title`, `meta`, `link`, `script` and `base` tags).

### CODE REVIEW

**Comment by stephan281094** [comment]
Looking good!

**Comment by somus** [comment]
@rdiazv PR looks great! There are some merge conflicts. I'll be happy to merge after you fix those conflicts.

**Comment by rdiazv** [comment]
@somus: done 👍

**Comment by carloscuatin** [comment]
LGTM 👍

**Comment by somus** [comment]
@rdiazv  Awesome! 👍 Thanks for the quick reply and your patience. I'm sorry it took us so long to merge this.

From now on, we will actively work on mern. I've opened a discussion thread for mern v2 at #146. It would be great if you could take a look and give some suggestions.

**Pull request merged**
