### PR TITLE
server error reporting plus linter updates

### PR DESCRIPTION
**Pull request by sirrodgepodge**

### CODE REVIEW

**Comment by SOSANA** [comment]
add in those curly braces

**Comment by SOSANA** [comment]
@sirrodgepodge thing that sucks is if we put in no-shadow won't catch other errors in future...maybe just turning off eslint rule for a specific line for pr #112 as shown below broski

```
// Server Side Rendering based on routes matched by React-router.
import Post from '../models/post';
import cuid from 'cuid';
import slug from 'slug';
import sanitizeHtml from 'sanitize-html';

export function getPosts(req, res) {
  Post.find().sort('-dateAdded').exec((err, posts) => {
    if (err) {
      return res.status(500).send(err);
    }
    return res.json({ posts });
  });
}

export function addPost(req, res) {
  if (!req.body.post.name || !req.body.post.title || !req.body.post.content) {
    return res.status(403).end();
  }

  const newPost = new Post(req.body.post);

  // Let's sanitize inputs
  newPost.title = sanitizeHtml(newPost.title);
  newPost.name = sanitizeHtml(newPost.name);
  newPost.content = sanitizeHtml(newPost.content);

  newPost.slug = slug(newPost.title.toLowerCase(), { lowercase: true });
  newPost.cuid = cuid();
  return newPost.save((err, saved) => {
    if (err) {
      return res.status(500).send(err);
    }
    return res.json({ post: saved });
  });
}

export function getPost(req, res) {
  const newSlug = req.query.slug.split('-');
  const newCuid = newSlug[newSlug.length - 1];
  Post.findOne({ cuid: newCuid }).exec((err, post) => {
    if (err) {
      return res.status(500).send(err);
    }
    return res.json({ post });
  });
}

export function deletePost(req, res) {
  const postId = req.body.postId;
  Post.findById(postId).exec((err, post) => {
    if (err) {
      return res.status(500).send(err);
    }

    return post.remove(() => {
      res.status(200).end();
    });
  });
}
```

**Comment by SOSANA** [comment]
@sirrodgepodge make sure to add in those curly braces and return the values :+1:

**Comment by sirrodgepodge** [comment]
k, will do later tonight lol, too much time spent on codewars :P

**Comment by somus** [comment]
@sirrodgepodge Thanks for the PR! I merged another similar PR which forwards the error to console before seeing this one. Sorry. I think printing stack trace on the screen would be good. As @SOSANA suggested, If you could remove those eslint rules, I'll be more than happy to merge. :)

**Pull request closed without merging**
