### PR TITLE
add scss support and make nodemon development server

### PR DESCRIPTION
**Pull request by evansendra**
SCSS support in development and production.

In dev, works by bundling with the javascript so that it works with the HMR.  In production, works by generating app.css using `sass` command then minifying to app.min.css and inserting into `client/index.js`. 

To test:
* confirm `npm start` works as intended
* confirm `npm run-script start:prod` works as intended

### CODE REVIEW

**Comment by beaucharman** [comment]
I feel stripping out support for vanilla css, and only supporting one CSS preprocessor is a step in the wrong direction. Could you alter this PR to *add* Sass support rather than a full swap out?

**Comment by mayankchd** [comment]
Agree with @beaucharman !

**Comment by evansendra** [comment]
makes sense, I'll modify

**Comment by pomeo** [comment]
@evansendra @beaucharman @mayankchd Why use SCSS if exists PostCSS and SCSS parser for PostCSS?
PostCSS at the moment already have among modules mern-starter.

**Comment by raksonibs** [comment]
Thanks @evansendra. Looks good!

**Comment by evansendra** [comment]
@beaucharman @mayankchd this should be modified appropriately now.  Let me know if you see anything else that needs fixing before a potential merge!

**Comment by carloscuatin** [comment]
I think the style file must be imported on the client and define it in a variable in webpack with this make the user choose the value of that variable

sass

**Comment by SOSANA** [comment]
@carloscuatin can we create a seperate PR for nodemon? so we can get this merged ASAP

@beaucharman I agree, what if we want to do inline styling like radium? I think adding scss support should be applied to the scaffolding aspect so you can choose at start of the project

@prank7 @mayankchd @carloscuatin thoughts?

**Comment by evansendra** [comment]
Yeah if we want to add this to the scaffolding part I think that could be a separate PR in mern-cli and then  I could remove the style folder with the SCSS and just leave the rules in the webpack config files

**Comment by yn5** [comment]
What's the status on this? Would be great to have SCSS support in master. The scaffolding could maube be added later right?

**Comment by raksonibs** [comment]
Hey @yn5 I'll take a look at this later this weekend!

**Comment by Bonitis** [comment]
Hey @evansendra wanted to let you know that I tested this code and it worked perfectly for me. Also, I think that you missed an opportunity to name the script sassinate. ^___^

**Comment by stephenrichter** [comment]
Hi there, also wanted to comment and say thanks for this @evansendra. Manually added this code to my project and SCSS is working well and the "watch-sass" is a great addition. Cheers!

**Comment by somus** [comment]
PostCSS with css-modules is implemented on v2 branch(510101fbaadfce16d58134e21d6d3528e886febd). Closing this in favour of that. Thank you very much for your effort, @evansendra.

**Pull request closed without merging**
