### PR TITLE
fix in redux-devtools

### PR DESCRIPTION
**Pull request by carloscuatin**
prevent initial double render,
add support for redux-devtools-extension

redux-devtools-extension

### CODE REVIEW

**Comment by SOSANA** [comment]
@carloscuatin never even knew about that chrome ext. I just downloaded it this morning! Think we should mention of it on readme? what if we want to use a different browser for testing? can we still pop up redux side bar if needed?

**Comment by carloscuatin** [comment]
@SOSANA clear can still use another browser if you have the extension will render the normal redux-devtools

**Comment by SOSANA** [comment]
thanks for explanation @carloscuatin  LGTM

**Comment by prank7** [comment]
LGTM, Merging it. Thanks @carloscuatin

**Pull request merged**
