### PR TITLE
fixing server.js eslint errors

### PR DESCRIPTION
**Pull request by SOSANA**
fixing the following eslint errors
- Require Consistent Returns (consistent-return)
  `Unexpected string concatenation.at line 81 col 5 in server\server.js`
- Disallow Shadowing (no-shadow)
  `Expected to return a value at the end of this function.at line 87 col 77 in server\server.js`
- Suggest using template literals instead of string concatenation. (prefer-template)
 ` 'err' is already declared in the upper scope.at line 115 col 14 in server\server.js`

### CODE REVIEW

**Comment by sirrodgepodge** [comment]
duuuuuude!   This is no good, it gets rid of sending error to the server completely, instead we should just change .eslintrc to allow some really common names to be "shadowed" IMO, done by adding this line to "rules":

"no-shadow": [1, { "allow": ["done", "resolve", "reject", "done", "cb", "err", "error"] }]

Thoughts?

Will make a PR later tonight

**Comment by SOSANA** [comment]
Err is defined in upper scope !!! but ya .catch() could be put back in and no-shadow applied

**Comment by sirrodgepodge** [comment]
fair fair, changed to "serverError" in this case, generally I think it might be good to relax that rule for labels such as "callback", "done", etc., PR here:
https://github.com/Hashnode/mern-starter/pull/112

**Comment by SOSANA** [comment]
@sirrodgepodge thing that sucks is if we put in no-shadow won't catch other errors in future...maybe just add turning off eslint rule for a specific line for pr #112 as shown below broski

```
// Server Side Rendering based on routes matched by React-router.
app.use((req, res, next) => {
  match({ routes, location: req.url }, (err, redirectLocation, renderProps) => {
    if (err) {
      return res.status(500).end(renderError(err));
    }

    if (redirectLocation) {
      return res.redirect(302, redirectLocation.pathname + redirectLocation.search);
    }
  

    if (!renderProps) {
      return next();
    }
      

    const initialState = { posts: [], post: {} };

    const store = configureStore(initialState);

    return fetchComponentData(store, renderProps.components, renderProps.params)
      .then(() => {
        const initialView = renderToString(
          <Provider store={store}>
            <RouterContext {...renderProps} />
          </Provider>
        );
        const finalState = store.getState();

        res.status(200).end(renderFullPage(initialView, finalState));
      })
      .catch(serverError => res.status(500).end(renderError(serverError))); / eslint-disable-line no-use-before-define
  }); 
});
```

**Pull request merged**
