### PR TITLE
add redux saga

### LINKED ISSUE #97: Use redux-saga instead of redux-thunk
How about this?

### PR DESCRIPTION
**Pull request by somus**
Fixes #97

### CODE REVIEW

**Comment by mayankchd** [comment]
Sorry for being late on this. Any chance you can take a pull and solve merge conflict. Happy to merge after that!

**Comment by carloscuatin** [comment]
@somus you just need to update your repository and then do git push origin master --force and ready,
I am also happy that finally this request fusion extraction

**Comment by somus** [comment]
Just noticed redux sagas breaks during server-side rendering since there are no promises returned from the fetch actions. I checked redux-saga repo, server rendering is not quite there yet. 🙁  But there are some ideas in this yelouafi/redux-saga#13. I will try to implement it.

**Comment by jforaker** [comment]
Just my two cents but as a huge fan of this project, I don't think this should be merged to master. Reason is plain Redux has a significantly easier barrier to entry for newcomers, and Saga is largely complex abstraction that is not necessary and does not provide any substantial improvements over the current architecture. I've shipped multiple production level Redux apps and even I cannot wrap my head around sagas, nor have I needed to. Also saying "fixes #97" is a bit of a smoke screen as it is not really an issue, its one person's request.

**Comment by somus** [comment]
@jforaker Thanks for the input. What are you saying makes sense. Redux saga is quite complex. To keep the project beginner friendly, it is better not to add sagas. Do you think it is a better idea to have a separate project forked from mern for advanced users?

**Comment by carloscuatin** [comment]
I would believe that we can handle mern-cli flags and if a project would be interesting for advanced users but this generated confusion for new, it is my humble opinion

**Comment by aaronmcadam** [comment]
I know this is an old PR, but the server-side rendering is broken because the saga functions don't return promises: 

```
TypeError: consumer(...).then is not a function
    at runner (promiseUtils.js:11:10)
    at sequence (promiseUtils.js:20:10)
    at fetchComponentData (fetchData.js:11:10)
    at server.js:104:5
```

I think the solution is to separate the requests for the data needs from the saga, say a helper function, and use that in `Component.need` instead. What do you think?

**Comment by somus** [comment]
@aaronmcadam This error comes because saga doesn't return a promise. One way to handle this situation is to make `getPost` function consuming `requestUrl` function to retrieve the posts which will return a promise. Use this function in your `Component.need` array, not the saga. You can use the same function for saga's `yield`. Let me know, if it works.

**Comment by aaronmcadam** [comment]
Hi @somus, thanks for getting back to me! I ended up following the [official `redux-saga` universal example](https://github.com/yelouafi/redux-saga/blob/master/examples/real-world/sagas/index.js), which runs the saga on the backend too. The example there doesn't need the `need` static anymore because data fetching all handled by the lifecycle methods.

**Pull request closed without merging**
