### PR TITLE
Hapi branch

### PR DESCRIPTION
**Pull request by camerow**
This is a very WIP version of Hapi-MRN - running into some stumbling points, anyone w/ more knowledge please feel free to help me out! =D

### CODE REVIEW

**Comment by camerow** [comment]
Also not actually wanting this to get merged in - sorry if there is a better way of doing this. If there is let me know and I'll change it. Cheers!

**Comment by prank7** [comment]
@camerow Thanks for this PR. Looks interesting. 
I will take a look at it later and let you know how we can accomodate this. :+1:

**Comment by camerow** [comment]
Thanks @prank7. I'm getting a few errors that are stumping me as I'm pretty new to this isomorphic stuff (only written one basic app w/ this pattern) - namely renderProps is coming in as an object w/ components, and then comes in undefined. 0.o

**Comment by prank7** [comment]
@camerow I hope this [documentation](http://mern.io/documentation.html#server) helps you there. It comes from [React-Router](https://github.com/reactjs/react-router/blob/master/docs/API.md#utilities). Try logging it to understand what it returns.

**Comment by camerow** [comment]
Here is my output, I'm curious why `fetchComponentData(...)` is being called so many times. 

```
RENDER PROPS { routes: 
   [ { path: '/',
       component: [Object],
       indexRoute: [Object],
       childRoutes: [Object] },
     { component: [Object] } ],
  params: {},
  location: 
   { pathname: '/',
     search: '',
     hash: '',
     state: null,
     action: 'POP',
     key: 'p4e5gh',
     query: {} },
  components: 
   [ { [Function: Connect]
       displayName: 'Connect(App)',
       WrappedComponent: [Object],
       contextTypes: [Object],
       propTypes: [Object] },
     { [Function: Connect]
       displayName: 'Connect(PostContainer)',
       WrappedComponent: [Object],
       contextTypes: [Object],
       propTypes: [Object],
       need: [Object] } ],
  history: 
   { listenBefore: [Function],
     listen: [Function],
     transitionTo: [Function],
     push: [Function],
     replace: [Function],
     go: [Function],
     goBack: [Function],
     goForward: [Function],
     createKey: [Function],
     createPath: [Function],
     createHref: [Function],
     createLocation: [Function],
     setState: [Function],
     registerTransitionHook: [Function],
     unregisterTransitionHook: [Function],
     pushState: [Function],
     replaceState: [Function],
     isActive: [Function],
     match: [Function],
     listenBeforeLeavingRoute: [Function] },
  router: 
   { listenBefore: [Function: listenBefore],
     listen: [Function: listen],
     transitionTo: [Function: transitionTo],
     push: [Function: push],
     replace: [Function: replace],
     go: [Function: go],
     goBack: [Function: goBack],
     goForward: [Function: goForward],
     createKey: [Function: createKey],
     createPath: [Function: createPath],
     createHref: [Function: createHref],
     createLocation: [Function: createLocation],
     setState: [Function],
     registerTransitionHook: [Function],
     unregisterTransitionHook: [Function],
     pushState: [Function],
     replaceState: [Function],
     __v2_compatible__: true,
     setRouteLeaveHook: [Function: listenBeforeLeavingRoute],
     isActive: [Function: isActive] },
  matchContext: 
   { history: 
      { listenBefore: [Function],
        listen: [Function],
        transitionTo: [Function],
        push: [Function],
        replace: [Function],
        go: [Function],
        goBack: [Function],
        goForward: [Function],
        createKey: [Function],
        createPath: [Function],
        createHref: [Function],
        createLocation: [Function],
        setState: [Function],
        registerTransitionHook: [Function],
        unregisterTransitionHook: [Function],
        pushState: [Function],
        replaceState: [Function],
        isActive: [Function],
        match: [Function],
        listenBeforeLeavingRoute: [Function] },
     transitionManager: 
      { isActive: [Function: isActive],
        match: [Function: match],
        listenBeforeLeavingRoute: [Function: listenBeforeLeavingRoute],
        listen: [Function: listen] },
     router: 
      { listenBefore: [Function: listenBefore],
        listen: [Function: listen],
        transitionTo: [Function: transitionTo],
        push: [Function: push],
        replace: [Function: replace],
        go: [Function: go],
        goBack: [Function: goBack],
        goForward: [Function: goForward],
        createKey: [Function: createKey],
        createPath: [Function: createPath],
        createHref: [Function: createHref],
        createLocation: [Function: createLocation],
        setState: [Function],
        registerTransitionHook: [Function],
        unregisterTransitionHook: [Function],
        pushState: [Function],
        replaceState: [Function],
        __v2_compatible__: true,
        setRouteLeaveHook: [Function: listenBeforeLeavingRoute],
        isActive: [Function: isActive] } } }
NO PROPS! undefined
NO PROPS! undefined
Warning: Failed propType: Required prop `posts` was not specified in `PostContainer`. Check the render method of `Connect(PostContainer)`.
Warning: Failed propType: Required prop `posts` was not specified in `PostListView`. Check the render method of `Connect(PostListView)`.
NO PROPS! undefined
NO PROPS! undefined
```

is `app.use((req, res) => { ... }` the equivalent of a root ("/") route?

**Comment by camerow** [comment]
Kind of answered my own question, I was using "/{params*}" which was triggering that route on all requests, so I used `"/"`. Now I'm catching an error `ERROR [TypeError: Cannot read property 'map' of undefined]`. 

Sorry I've I'm barraging you, I'm kind of using this as a medium to think through my problems =D.

**Comment by camerow** [comment]
It renders! The controllers need some love, I've never used MongoDB at all, let alone with Hapi so I'll have to improve that and get those actions firing, but it renders! Yay! This is my first fairly large open-source contribution so I'm very excited. YESSSS!

**Comment by camerow** [comment]
Fixed addPost and deletePost

**Comment by prank7** [comment]
Great work! Glad you figured it out.
I am not sure how to include this PR in this project yet. However, I will point anyone looking for HAPI implementation to your forked repo. :+1:

**Comment by somus** [comment]
Thanks for the PR. As Prashant said, we will be happy to point someone to your project who needs hapi verison of MERN.

**Comment by camerow** [comment]
Great! Thanks for your hard work making cool stuff! =)

**Pull request closed without merging**
