### PR TITLE
restart server development

### PR DESCRIPTION
**Pull request by carloscuatin**
nodemon add to restart the server when there are changes only in the folder server

nodemon

### CODE REVIEW

**Comment by SOSANA** [comment]
LGTM

**Comment by carloscuatin** [comment]
@SOSANA  ??

**Comment by SOSANA** [comment]
@carloscuatin ???

**Comment by bguzryanto** [comment]
@carloscuatin LGTM stand for Looks Good To Me.

**Comment by carloscuatin** [comment]
@SOSANA I do not understand what did you mean me LGTM

**Comment by carloscuatin** [comment]
@bguzryanto oh yeah

**Comment by SOSANA** [comment]
@carloscuatin LGTM (Lets Get This Merged)

**Comment by bguzryanto** [comment]
@SOSANA whoops, after all this time I thought it was Look good to me. :feelsbadman:

**Comment by SOSANA** [comment]
@bguzryanto both work broski

**Comment by evansendra** [comment]
+1 ... also added in #50

**Comment by carloscuatin** [comment]
at #50 recharge server is added in any changes so is the client and that is not what I expected, because the transform react not serve and opened to remove it. Recharging solomante server should occur when there is a change in the server folder

**Comment by carloscuatin** [comment]
@mayankchd closing the end because I'm doing an implementation of REACT-router-redux and not have conflict with this request

**Comment by mayankchd** [comment]
Okay...

**Pull request closed without merging**
